# Generated by Django 3.2.5 on 2021-07-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product_name', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('nutriscore_grade', models.CharField(max_length=2)),
                ('imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('userpw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.db_product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.user_db')),
            ],
        ),
    ]
