# Generated by Django 3.2.5 on 2021-07-16 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_favorite_db_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_db',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
