# Generated by Django 3.2.5 on 2021-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_auto_20210716_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='db_product',
            name='categories',
        ),
        migrations.AddField(
            model_name='db_product',
            name='category_id',
            field=models.ManyToManyField(blank=True, related_name='categories', to='accueil.Category_db'),
        ),
    ]
