# Generated by Django 3.2.5 on 2021-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_auto_20210716_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_db',
            name='category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
