# Generated by Django 3.2.5 on 2021-07-19 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0006_alter_category_db_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_product',
            name='image_small_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
