# Generated by Django 3.2.5 on 2021-07-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0009_auto_20210722_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
