# Generated by Django 3.2.5 on 2021-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0011_rename_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
