# Generated by Django 3.2.5 on 2021-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0012_auto_20210727_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='accueil.Category'),
        ),
    ]
